sudo: required
language: generic

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-2
  app: hackathon-bookzz-app
  env: HackathonBookzzApp-env
  bucket_name: elasticbeanstalk-ap-southeast-2-334708000698
  bucket_path: hackathon-bookzz-app
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
