language: node_js
node_js:
  - 12
before_script:
  - npm install

script:
  - npm test

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: bookzz-backend
  env: BookzzBackend-env
  bucket_name: elasticbeanstalk-ap-southeast-1-334708000698
  bucket_path: bookzz-backend
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
